require('setup')
require('mapping')
require('plugins')
require('plugins_setup.nvim-tree')
require('plugins_setup.lualine')
require('plugins_setup.nvim-autopairs')
require('plugins_setup.ale')
require('plugins_setup.treesitter')
